Areas/Forms/Models/AjaxFormModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Sdl.Web.Common.Models;
using Navient.Modules.Forms.Areas.Forms.Models;

namespace Navient.Modules.Forms.Areas.Forms.Models
{
    [SemanticEntity(EntityName ="Form", Prefix = "a", Vocab = "http://www.sdl.com/web/schemas/forms")]
    public class AjaxFormModel : BaseFormModel
    {
        public string Heading { get; set; }

        public RichText Subheading { get; set; }

        public Article SuccessRedirect { get; set; }
        public Article ErrorRedirect { get; set; }
    }
}

Areas/Forms/Models/Article.cs
using Sdl.Web.Common.Models;
using System;
using System.Collections.Generic;
using System.Net.Mime;
using Sdl.Web.Common.Configuration;

namespace DXA.Modules.Forms.Areas.Forms.Models
{
    public class Article : EntityModel
    {
        [SemanticProperty("s:headline")]
        public string Headline { get; set; }
        
        [SemanticProperty("s:dateCreated")]
        public DateTime? Date { get; set; }
        [SemanticProperty("s:about")]
        public string Description { get; set; }
        [SemanticProperty("s:articleBody")]
        public List<Paragraph> ArticleBody { get; set; }
    }
}

Areas/Forms/Models/AudienceManagerPostActionModel.cs
using Sdl.Web.Common.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DXA.Modules.Forms.Areas.Forms.Models
{
    [SemanticEntity(EntityName = "AudienceManagerPostAction", Prefix = "a", Vocab = CoreVocabulary)]
    public class AudienceManagerPostActionModel : BaseFormPostActionModel
    {
        public string IdentificationKeyConfig { get; set; }

        public string IdentificationSource { get; set; }

        public string EmailConfirmationIdentifier { get; set; }

        public int AddressBookId { get; set; }

    }
}

Areas/Forms/Models/BaseFormModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Sdl.Web.Common.Models;

namespace DXA.Modules.Forms.Areas.Forms.Models
{
   [SemanticEntity(EntityName ="Form", Prefix = "b", Vocab = "http://www.sdl.com/web/schemas/forms")]
    public class BaseFormModel : EntityModel
    {
        public string Heading { get; set; }

        public RichText Subheading { get; set; }

        [SemanticProperty("b:formField")]
        public List<FormFieldModel> FormFields { get; set; }

    }
}

Areas/Forms/Models/BaseFormPostActionModel.cs
using Sdl.Web.Common.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DXA.Modules.Forms.Areas.Forms.Models
{
    //[SemanticEntity(EntityName = "PostActionObject", Prefix = "p", Vocab = "http://www.sdl.com/web/schemas/forms")]
    public abstract class BaseFormPostActionModel : EntityModel
    {
        //[SemanticProperty("p:formHandler")]
        public string FormHandler { get; set; }

    }
}

Areas/Forms/Models/EmailPostActionModel.cs
using Sdl.Web.Common.Models;
using System.Collections.Generic;

namespace DXA.Modules.Forms.Areas.Forms.Models
{
    [SemanticEntity(EntityName = "EmailPostAction", Prefix="e", Vocab = CoreVocabulary)]
    public class EmailPostActionModel : BaseFormPostActionModel
    {
        
        [SemanticProperty("e:to")]
        public List<string> To { get; set; }
        public List<string> Cc { get; set; }
        public string Subject { get; set; }
        public RichText EmailBody { get; set; }
    }
}

Areas/Forms/Models/FormCollectionModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Sdl.Web.Common.Models;

namespace DXA.Modules.Forms.Areas.Forms.Models
{
    [SemanticEntity(EntityName = "genericFormCollection", Prefix = "tri", Vocab = CoreVocabulary)]
    public class FormCollectionModel : EntityModel
    {

        [SemanticProperty("tri:title")]
        public string SectionTitle { get; set; }

        [SemanticProperty("tri:description")]
        public RichText Description { get; set; }

        [SemanticProperty("tri:addnDescription")]
        public RichText AdditionalDescription { get; set; }

        [SemanticProperty("tri:forms")]
        public List<FormModel> Forms { get; set; }

        [SemanticProperty("tri:successRedirect")]
        public Link SuccessRedirect { get; set; }
        [SemanticProperty("tri:errorRedirect")]
        public Link ErrorRedirect { get; set; }

        [SemanticProperty("tri:submitButtonLabel")] 
        public string SubmitButtonLabel { get; set; }
        [SemanticProperty("tri:formPostAction")]
        public List<BaseFormPostActionModel> FormPostActions { get; set; }

        [SemanticProperty("tri:customCSS")]
        public Tag CustomCSS { get; set; }

        [SemanticProperty("tri:enableRecaptcha")]
        public string EnableRecaptcha { get; set; }

    }
}

Areas/Forms/Models/FormModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Sdl.Web.Common.Models;

namespace DXA.Modules.Forms.Areas.Forms.Models
{
    [SemanticEntity(EntityName ="Form", Prefix = "b", Vocab = "http://www.sdl.com/web/schemas/forms")]
    [SemanticEntity(EntityName = "genericFormTile", Prefix = "a", Vocab = CoreVocabulary)]
    public class FormModel : BaseFormModel
    {
       

        [SemanticProperty("a:description")]
        public RichText Description { get; set; }

        [SemanticProperty("a:addnDescription")]
        public RichText AddnDescription { get; set; }

        [SemanticProperty("b:formCustomCSS")]
        public Tag FormCustomCSS { get; set; }

        [SemanticProperty("a:tileCustomCSS")]
        public Tag TileCustomCSS { get; set; }
    }
}

Areas/Forms/Models/GenericFormTile.cs
using Sdl.Web.Common.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DXA.Modules.Forms.Areas.Forms.Models
{
    
 [SemanticEntity(EntityName = "genericFormTile", Prefix = "a", Vocab = CoreVocabulary)]
    public class GenericFormTile : EntityModel
    {
        [SemanticProperty("a:heading")]
        public string Heading { get; set; }

        [SemanticProperty("a:subHeading")]
        public string SubHeading { get; set; }

        [SemanticProperty("a:description")]
        public RichText Description { get; set; }

        [SemanticProperty("a:addnDescription")]
        public RichText AddnDescription { get; set; }

        [SemanticProperty("a:tileCustomCSS")]
        public Tag TileCustomCSS { get; set; }
    }
}

Areas/Forms/Models/Paragraph.cs
using Sdl.Web.Common.Models;
using System;

namespace DXA.Modules.Forms.Areas.Forms.Models
{
    [Serializable]
    public class Paragraph : EntityModel
    {
        public string Subheading { get; set; }
        public RichText Content { get; set; }
        public MediaItem Media { get; set; }
        public string Caption { get; set; }
    }
}

Areas/Forms/Models/SalesforcePostActionModel.cs
using Sdl.Web.Common.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DXA.Modules.Forms.Areas.Forms.Models
{
    [SemanticEntity(EntityName = "SalesforcePostAction", Prefix = "s", Vocab = CoreVocabulary)]
    public class SalesforcePostActionModel : BaseFormPostActionModel
    {
        public string OrganizationId { get; set; }

        public string ParameterTwo { get; set; }

    }
}

Areas/Forms/Controllers/FormsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Web.Helpers;

using DXA.Modules.Forms.Areas.Forms.FormHandlers;
using DXA.Modules.Forms.Areas.Forms.Models;
using DXA.Modules.Forms.Areas.Forms.Providers;
using Newtonsoft.Json.Linq;

using Sdl.Web.Common.Logging;
using Sdl.Web.Common.Models;
using Sdl.Web.Mvc.Configuration;
using Sdl.Web.Mvc.Controllers;

namespace DXA.Modules.Forms.Areas.Forms.Controllers
{
    //
    public class FormsController : EntityController
    {
        protected override ViewModel EnrichModel(ViewModel model)
        {


            FormCollectionModel baseFormCollection = base.EnrichModel(model) as FormCollectionModel;

            if (baseFormCollection != null)
            {
                if (baseFormCollection.Forms != null)
                {
                    if (Request.HttpMethod == "POST")
                    {
                        bool status = true;

                        // MapRequestFormData validates model as well
                        MapRequestFormData(baseFormCollection.Forms);

                        if (string.Compare(baseFormCollection.EnableRecaptcha, "Enable") == 0)
                        {

                            var response = Request["g-recaptcha-response"];
                            string secretKey = WebRequestContext.Localization.GetConfigValue("core.recaptchaSecretKey");

                            var client = new WebClient();
                            var result = client.DownloadString(string.Format(WebRequestContext.Localization.GetConfigValue("core.recaptchaValidateUrl"), secretKey, response));
                            var obj = JObject.Parse(result);
                            status = (bool)obj.SelectToken("success");
                            ViewBag.Message = status ? "" : WebRequestContext.Localization.GetConfigValue("core.recaptchaErrorMessage");
                        }
                        if (ModelState.IsValid && status)
                        {

                            try
                            {
                                // Loading the OptionCategory list from TemData to avoid broker calls
                                foreach (var form in baseFormCollection.Forms)
                                {
                                    if (form.FormFields != null)
                                    {


                                        foreach (var field in form.FormFields.Where(f => !string.IsNullOrEmpty(f.OptionsCategory)))
                                        {
                                            if (field.FieldType == FieldType.DropDown || field.FieldType == FieldType.CheckBox || field.FieldType == FieldType.RadioButton)
                                            {

                                                field.OptionsCategoryList = TempData[field.Name] as List<OptionModel>;


                                            }
                                        }


                                    }
                                }
                                //Add logic to save form data here
                                foreach (var postAction in baseFormCollection.FormPostActions)
                                {
                                    string formHandlerName = string.Empty;

                                    try
                                    {
                                        formHandlerName = postAction.FormHandler;

                                        var formHandler = FormHandlerRegistry.Get(formHandlerName);
                                        if (formHandler != null)
                                        {
                                            formHandler.ProcessForm(Request.Form, baseFormCollection.Forms.Where(form => form.FormFields != null).SelectMany(d => d.FormFields).ToList(), postAction);
                                        }
                                    }
                                    catch (Exception ex)
                                    {
                                        if (!string.IsNullOrEmpty(baseFormCollection.ErrorRedirect.Url))
                                        {
                                            Log.Error(ex, "Error occured while processing form data with form handler: {0}. Error message: {1}", formHandlerName, ex.Message);
                                            return new RedirectModel(baseFormCollection.ErrorRedirect.Url);
                                        }
                                        else
                                        {
                                            throw ex;
                                        }
                                    }
                                }

                                if (!string.IsNullOrEmpty(baseFormCollection.SuccessRedirect.Url))
                                    return new RedirectModel(baseFormCollection.SuccessRedirect.Url);
                                else
                                    return new RedirectModel(WebRequestContext.Localization.Path);
                            }
                            catch (Exception ex)
                            {
                                if (!string.IsNullOrEmpty(baseFormCollection.ErrorRedirect.Url))
                                {
                                    Log.Error(ex, "Error occured while saving form data.");
                                    return new RedirectModel(baseFormCollection.ErrorRedirect.Url);
                                }
                                else
                                    throw ex;
                            }


                        }
                    }
                    else
                    {
                        // Load options from category
                        foreach (var form in baseFormCollection.Forms)
                        {
                            if (form.FormFields != null)
                            {


                                foreach (var field in form.FormFields.Where(f => !string.IsNullOrEmpty(f.OptionsCategory)))
                                {
                                    if (field.FieldType == FieldType.DropDown || field.FieldType == FieldType.CheckBox || field.FieldType == FieldType.RadioButton)
                                    {

                                        List<OptionModel> options = TaxonomyProvider.LoadOptionsFromCategory(field.OptionsCategory, WebRequestContext.Localization);
                                        field.OptionsCategoryList = options.OrderBy(x => x.Key).ThenBy(x => x.DisplayText).ToList(); 

                                    }
                                }


                            }
                        }
                    }

                }

            }

            return baseFormCollection;

        }


        protected bool MapRequestFormData(List<FormModel> model)
        {
            if (Request.HttpMethod != "POST")
            {
                return false;
            }
            // CSRF protection: If the anti CSRF cookie is present, a matching token must be in the form data too.
            const string antiCsrfToken = "__RequestVerificationToken";
            if (Request.Cookies[antiCsrfToken] != null)
            {
                AntiForgery.Validate();
            }


            foreach (var form in model)
            {
                if (form.FormFields != null)
                {

                    foreach (string formField in Request.Form)
                    {
                        if (formField == antiCsrfToken)
                        {
                            // This is not a form field, but the anti CSRF token (already validated above).
                            continue;
                        }



                        FormFieldModel fieldModel = form.FormFields.FirstOrDefault(f => f.Name == formField);
                        if (fieldModel == null)
                        {
                            Log.Debug("Form [{0}] has no defined field for form field '{1}'", form.Id, formField);
                            continue;
                        }


                        List<string> formFieldValues = Request.Form.GetValues(formField).Where(f => f != "false").ToList();
                        try
                        {
                            fieldModel.Values = formFieldValues;
                        }
                        catch (Exception ex)
                        {
                            Log.Debug("Failed to set Model [{0}] property '{1}' to value obtained from form data: '{2}'. {3}", form.Id, fieldModel.Name, formFieldValues, ex.Message);
                            ModelState.AddModelError(fieldModel.Name, ex.Message);
                        }

                        FormFieldValidator validator = new FormFieldValidator(fieldModel);
                        string validationMessage = "Field Validation Failed";
                        if (!validator.Validate(formFieldValues, ref validationMessage))
                        {
                            if (validationMessage != null)
                            {
                                Log.Debug("Validation of property '{0}' failed: {1}", fieldModel.Name, validationMessage);
                                ModelState.AddModelError(fieldModel.Name, validationMessage);
                                continue;
                            }
                        }


                    }
                }
            }

            return true;
        }


    }

    public class FormFieldValidator
    {
        FormFieldModel field;

        public FormFieldValidator(FormFieldModel fieldDefinition)
        {
            field = fieldDefinition;
        }

Areas/Forms/Views/Forms/AjaxForm.cshtml
@using System.Web.Mvc.Ajax

@model AjaxFormModel

<div id="form">
    @using (Ajax.BeginForm("ProcessAjaxForm", "Forms", new AjaxOptions { UpdateTargetId = "form" }))
    {

    @Html.AntiForgeryToken()
    <h1>@Model.Heading</h1>
    <p>@Html.DxaRichText(Model.Subheading)</p>

    foreach (var field in Model.FormFields)
    {

        switch (field.FieldType)
        {
            case FieldType.Text:
                @Html.Partial("Partials/Text", field);
                break;

            case FieldType.TextArea:
                @Html.Partial("Partials/TextArea", field);
                break;

            case FieldType.DropDown:
                @Html.Partial("Partials/DropDown", field);
                break;

            case FieldType.CheckBox:
                @Html.Partial("Partials/CheckBox", field);
                break;

            case FieldType.RadioButton:
                @Html.Partial("Partials/RadioButton", field);
                break;

            case FieldType.Date:
                @Html.Partial("Partials/Date", field);
                break;
        }
    }
    <input type="hidden" name="formId" value="@Model.Id" />
    <button type="submit" class="btn btn-default">@Model.SubmitButtonLabel</button>
    }
</div>

Areas/Forms/Views/Forms/ErrorResult.cshtml
@model Article

<div class="content">
    <h1>@Model.Headline</h1>
    @if (Model.ArticleBody != null)
    {
        foreach (var para in Model.ArticleBody)
        {
            <div>
                @Html.DxaRichText(para.Content)
            </div>
        }
    }
</div>

Areas/Forms/Views/Forms/Form.cshtml
@model FormModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form">
        <h1>@Model.Heading</h1>
        <p>@Html.DxaRichText(Model.Subheading)</p>
    
        @foreach (var field in Model.FormFields)
        {

            switch (field.FieldType)
            {
                case FieldType.Text:
                    @Html.Partial("Partials/Text", field);
                    break;

                case FieldType.TextArea:
                    @Html.Partial("Partials/TextArea", field);
                    break;

                case FieldType.DropDown:
                    @Html.Partial("Partials/DropDown", field);
                    break;

                case FieldType.CheckBox:
                    @Html.Partial("Partials/CheckBox", field);
                    break;

                case FieldType.RadioButton:
                    @Html.Partial("Partials/RadioButton", field);
                    break;

                case FieldType.Date:
                    @Html.Partial("Partials/Date", field);
                    break;
            }
        }

        <button type="submit" class="btn btn-default">@Model.SubmitButtonLabel</button>
        <script type="text/javascript">
                //$(function () {
                //    
                //    $('.datepicker').datepicker({
                //        todayHighlight: true
                //    });
                //});

            //(function ($) {
            
            //    $.validator.unobtrusive.adapters.add("mandatory", function (options) {
            //        options.rules["required"] = true;
            //        if (options.message) {
            //            options.messages["required"] = options.message;
            //        }
            //    });
            //}(jQuery));

            //(function ($) {
            //    $.validator.unobtrusive.adapters.addBool("mandatory", "required");
            //}());

        </script>
    </div>
}

Areas/Forms/Views/Forms/GenericFormTile-6-Column.cshtml
@model DXA.Modules.Forms.Areas.Forms.Models.FormCollectionModel
@using System.Configuration;
@{
    Layout = null;
    if (Model == null)
    {
        return;
    }
    var css = Model.CustomCSS != null ? Model.CustomCSS.Key : string.Empty;
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form">
        <section class="row @css">
            @if (Model.SectionTitle != null)
            {

                <article class="col-xs-12 col-sm-12 col-md-12 formHeader">
                    <h1 @Html.DxaPropertyMarkup(() => Model.SectionTitle)>@Model.SectionTitle</h1>
                </article>
            }
            @if (Model.Description != null)
            {

                <article class="col-xs-12 col-sm-12 col-md-12 textTileTop">
                    <p @Html.DxaPropertyMarkup(() => Model.Description)>@Html.DxaRichText(Model.Description)</p>
                </article>
            }
            @if (Model.AdditionalDescription != null)
            {
                <article class="col-xs-12 col-sm-12 col-md-12 textTileTop">
                    <p @Html.DxaPropertyMarkup(() => Model.AdditionalDescription)>@Html.DxaRichText(Model.AdditionalDescription)</p>
                </article>
            }
            @if (Model.Forms != null)
            {
                string tileCss = string.Empty;
                foreach (var form in Model.Forms)
                {
                    tileCss = form.TileCustomCSS != null ? form.TileCustomCSS.Key : string.Empty;
                    if (form.FormFields != null)
                    {
                        var formCss = form.FormCustomCSS != null ? form.FormCustomCSS.Key : string.Empty;
                        <article class="col-xs-12 col-sm-12 col-md-6 @formCss">
                            @if (form.Heading != null)
                            {
                                <h1 @Html.DxaPropertyMarkup(() => form.Heading)>@form.Heading</h1>
                            }
                            @if (form.Subheading != null)
                            {
                                <p @Html.DxaPropertyMarkup(() => form.Subheading)>
                                    @Html.DxaRichText(form.Subheading)
                                </p>
                            }

                            @foreach (var field in form.FormFields)
                            {

                                switch (field.FieldType)
                                {
                                    case FieldType.Text:
                                        @Html.Partial("Partials/Text", field);
                                        break;

                                    case FieldType.TextArea:
                                        @Html.Partial("Partials/TextArea", field);
                                        break;

                                    case FieldType.DropDown:
                                        @Html.Partial("Partials/DropDown", field);
                                        break;

                                    case FieldType.CheckBox:
                                        @Html.Partial("Partials/CheckBox", field);
                                        break;

                                    case FieldType.RadioButton:
                                        @Html.Partial("Partials/RadioButton", field);
                                        break;

                                    case FieldType.Date:
                                        @Html.Partial("Partials/Date", field);
                                        break;
                                }
                            }



                        </article>
                    }
                    else
                    {

                        <article class="col-xs-12 col-sm-12 col-md-6 @tileCss">
                            @if (form.Heading != null)
                            {
                                <h1 @Html.DxaPropertyMarkup(() => form.Heading)>@form.Heading</h1>
                            }
                            @if (form.Description != null)
                            {
                                <p>
                                    @Html.DxaRichText(form.Description)
                                </p>
                            }
                        </article>
                    }

                }
                <article class="col-xs-12 col-sm-12 col-md-6 btnTile">
                    @*Render the button in the last form*@

                    @if (Model.EnableRecaptcha != null && string.Compare(Model.EnableRecaptcha, "Enable") == 0)
                    {
                        <div class="g-recaptcha recaptchaMsg" data-type="auto" data-callback="verifyCallback" data-sitekey="@WebRequestContext.Localization.GetConfigValue("core.recaptchaSiteKey")">

                        </div>
                        <div id="dvMessage" class="recaptchaMsg text-danger">
                            @ViewBag.Message
                        </div>
                    }

                    <button type="submit" id="btnSubmit" class="btn btn-default">@Model.SubmitButtonLabel</button>
                </article>
            }

        </section>
    </div>
}

Areas/Forms/Views/Forms/SuccessResult.cshtml
@model Article

<div class="content">
    <h1>@Model.Headline</h1>
    @if (Model.ArticleBody != null)
    {
        foreach (var para in Model.ArticleBody)
        {
                <div>
                    @Html.DxaRichText(para.Content)
                </div>
        }
    }
</div>